In [1]:
import numpy as np
import tensorflow as tf

C:\Program Files\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


#### Create input and convolutional filter
Where a is the input and b is the filter

In [7]:
a = np.reshape(np.arange(1,26),(5,5))
print('a:\n',a)
b= np.ones((3,3))*2
print('b:\n',b)

a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
b:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
A = 